"""
Report Generation Example

Demonstrates how to use the report generation service to create
professional HTML/PDF reports from AI analysis results.
"""

import asyncio
from pathlib import Path

# Import AI analysis
from src.ai import create_ai_analysis_service, AIAnalysisConfig

# Import report generation
from src.reports import (
    ReportGenerator,
    ReportConfig,
    ReportFormat,
    ReportTheme
)


async def generate_sample_report():
    """Generate a sample report from content analysis"""
    
    # Sample content to analyze
    sample_content = """
    Artificial Intelligence and Machine Learning in Healthcare
    
    The integration of artificial intelligence (AI) and machine learning (ML) in healthcare 
    is revolutionizing the medical industry. These technologies are enhancing diagnostic 
    accuracy, personalizing treatment plans, and improving patient outcomes across various 
    medical specialties.
    
    Key Applications:
    1. Medical Imaging Analysis: AI algorithms can detect abnormalities in X-rays, MRIs, 
       and CT scans with remarkable precision, often matching or exceeding human radiologists.
    
    2. Drug Discovery: Machine learning models accelerate the drug development process by 
       predicting molecular interactions and identifying promising compounds.
    
    3. Personalized Medicine: AI analyzes patient data to recommend tailored treatment 
       protocols based on individual genetic profiles and medical histories.
    
    4. Predictive Analytics: Healthcare providers use ML to forecast disease outbreaks, 
       patient deterioration, and resource needs.
    
    Challenges and Considerations:
    While the benefits are substantial, healthcare AI faces several challenges including 
    data privacy concerns, algorithmic bias, regulatory compliance, and the need for 
    clinician training. Ethical considerations around AI decision-making in life-critical 
    situations remain a topic of ongoing debate.
    
    Future Outlook:
    As AI technology continues to advance, we can expect even more sophisticated 
    applications in healthcare. The combination of AI with other emerging technologies 
    like genomics and wearable devices promises to create a truly personalized and 
    predictive healthcare system.
    
    Healthcare organizations must balance innovation with patient safety and privacy 
    while ensuring that AI serves as a tool to augment, not replace, human medical 
    expertise and compassion.
    """
    
    sample_title = "AI and Machine Learning in Healthcare: A Comprehensive Overview"
    sample_url = "https://example.com/ai-healthcare-analysis"
    
    print("=" * 70)
    print("REPORT GENERATION DEMONSTRATION")
    print("=" * 70)
    print()
    
    # Step 1: Perform AI analysis
    print("Step 1: Performing AI content analysis...")
    print("-" * 70)
    
    ai_service = await create_ai_analysis_service(
        provider="openai",
        model="gpt-4-turbo"
    )
    
    config = AIAnalysisConfig(
        summarize=True,
        analyze_sentiment=True,
        extract_topics=True,
        analyze_seo=True,
        score_readability=True,
        analyze_competitive=False,  # Skip competitive (no competitor data)
        max_concurrent=3,
        max_cost_usd=1.0
    )
    
    print(f"  • Analyzing: {sample_title}")
    print(f"  • Word count: {len(sample_content.split())} words")
    print(f"  • Running analyzers: {['Summary', 'Sentiment', 'Topics', 'SEO', 'Readability']}")
    print()
    
    analysis_result = await ai_service.analyze(
        content=sample_content,
        title=sample_title,
        url=sample_url,
        config=config
    )
    
    print(f"✓ Analysis complete!")
    print(f"  • Overall Quality: {analysis_result.overall_quality_score:.0f}/100")
    print(f"  • Processing Time: {analysis_result.total_processing_time_ms/1000:.1f}s")
    print(f"  • Analysis Cost: ${analysis_result.total_llm_cost:.4f}")
    print(f"  • Analyzers Run: {', '.join(analysis_result.analyzers_run)}")
    print()
    
    # Step 2: Generate HTML Report
    print("Step 2: Generating HTML report...")
    print("-" * 70)
    
    html_config = ReportConfig(
        format=ReportFormat.HTML,
        theme=ReportTheme.PROFESSIONAL,
        include_charts=True,
        include_recommendations=True,
        include_competitive=False,
        company_name="Content Analysis Platform",
        watermark="Generated by AI Content Analyzer"
    )
    
    report_generator = ReportGenerator(html_config)
    
    html_report = await report_generator.generate_report(
        analysis_result=analysis_result,
        title=sample_title,
        url=sample_url,
        config=html_config
    )
    
    # Save HTML report
    output_dir = Path("reports_output")
    output_dir.mkdir(exist_ok=True)
    
    html_path = output_dir / "analysis_report.html"
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_report.content)
    
    print(f"✓ HTML report generated!")
    print(f"  • File: {html_path}")
    print(f"  • Size: {html_report.file_size_bytes / 1024:.1f} KB")
    print(f"  • Sections: {html_report.sections_count}")
    print(f"  • Generation Time: {html_report.generation_time_ms:.0f}ms")
    print()
    
    # Step 3: Generate Markdown Report
    print("Step 3: Generating Markdown report...")
    print("-" * 70)
    
    md_config = ReportConfig(
        format=ReportFormat.MARKDOWN,
        theme=ReportTheme.PROFESSIONAL
    )
    
    report_generator_md = ReportGenerator(md_config)
    md_report = await report_generator_md.generate_report(
        analysis_result=analysis_result,
        title=sample_title,
        url=sample_url,
        config=md_config
    )
    
    md_path = output_dir / "analysis_report.md"
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(md_report.content)
    
    print(f"✓ Markdown report generated!")
    print(f"  • File: {md_path}")
    print(f"  • Size: {md_report.file_size_bytes / 1024:.1f} KB")
    print()
    
    # Step 4: Generate JSON Report
    print("Step 4: Generating JSON report...")
    print("-" * 70)
    
    json_config = ReportConfig(
        format=ReportFormat.JSON
    )
    
    report_generator_json = ReportGenerator(json_config)
    json_report = await report_generator_json.generate_report(
        analysis_result=analysis_result,
        title=sample_title,
        url=sample_url,
        config=json_config
    )
    
    json_path = output_dir / "analysis_report.json"
    with open(json_path, 'w', encoding='utf-8') as f:
        f.write(json_report.content)
    
    print(f"✓ JSON report generated!")
    print(f"  • File: {json_path}")
    print(f"  • Size: {json_report.file_size_bytes / 1024:.1f} KB")
    print()
    
    # Step 5: Try PDF generation
    print("Step 5: Attempting PDF generation...")
    print("-" * 70)
    
    pdf_config = ReportConfig(
        format=ReportFormat.PDF,
        theme=ReportTheme.PROFESSIONAL,
        include_charts=True,
        page_breaks=True
    )
    
    report_generator_pdf = ReportGenerator(pdf_config)
    pdf_report = await report_generator_pdf.generate_report(
        analysis_result=analysis_result,
        title=sample_title,
        url=sample_url,
        config=pdf_config
    )
    
    pdf_path = output_dir / "analysis_report.pdf"
    with open(pdf_path, 'wb') as f:
        f.write(pdf_report.content)
    
    if b"WeasyPrint library is not installed" in pdf_report.content:
        print(f"⚠ PDF generation requires WeasyPrint library")
        print(f"  • Install with: pip install weasyprint")
        print(f"  • Fallback file saved: {pdf_path}")
    else:
        print(f"✓ PDF report generated!")
        print(f"  • File: {pdf_path}")
        print(f"  • Size: {pdf_report.file_size_bytes / 1024:.1f} KB")
    print()
    
    # Summary
    print("=" * 70)
    print("REPORT GENERATION COMPLETE")
    print("=" * 70)
    print()
    print(f"All reports saved to: {output_dir.absolute()}")
    print()
    print("Reports generated:")
    print(f"  1. HTML:     {html_path.name} ({html_report.file_size_bytes / 1024:.1f} KB)")
    print(f"  2. Markdown: {md_path.name} ({md_report.file_size_bytes / 1024:.1f} KB)")
    print(f"  3. JSON:     {json_path.name} ({json_report.file_size_bytes / 1024:.1f} KB)")
    print(f"  4. PDF:      {pdf_path.name} ({pdf_report.file_size_bytes / 1024:.1f} KB)")
    print()
    print(f"Total analysis cost: ${analysis_result.total_llm_cost:.4f}")
    print()
    print("Open the HTML report in your browser to view the full interactive report!")
    print("=" * 70)


async def demonstrate_multiple_themes():
    """Generate reports with different themes"""
    
    print("\n" + "=" * 70)
    print("MULTIPLE THEMES DEMONSTRATION")
    print("=" * 70)
    print()
    
    # Quick analysis for demo
    ai_service = await create_ai_analysis_service()
    
    quick_result = await ai_service.quick_analysis(
        content="This is a brief demonstration of report theming capabilities.",
        title="Theme Demo"
    )
    
    # Mock a simple result for theming demo
    # (In real usage, use full analysis_result)
    
    themes = [
        ReportTheme.PROFESSIONAL,
        ReportTheme.MODERN,
        ReportTheme.MINIMAL,
        ReportTheme.COLORFUL
    ]
    
    output_dir = Path("reports_output/themes")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("Generating reports with different themes...")
    print()
    
    for theme in themes:
        print(f"  • {theme.value.title()} theme...")
        
        # Note: For this demo, we'd need a full analysis result
        # This is just to show the concept
        print(f"    Theme colors and styling applied")
    
    print()
    print(f"✓ Theme demonstrations would be saved to: {output_dir}")
    print()
    print("Available themes:")
    print("  • Professional: Blue/gray corporate style")
    print("  • Modern: Purple/teal contemporary design")
    print("  • Minimal: Black/white clean aesthetic")
    print("  • Colorful: Multi-color vibrant layout")
    print()


if __name__ == "__main__":
    print("\n🚀 Starting Report Generation Example\n")
    
    try:
        # Run main demonstration
        asyncio.run(generate_sample_report())
        
        # Uncomment to see theme demonstration
        # asyncio.run(demonstrate_multiple_themes())
        
    except KeyboardInterrupt:
        print("\n\n⚠ Interrupted by user")
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
